Add robust logic for shutting down WSO2 in stop script

diff --git a/extras/pbbundler/smrtlink_services_ui/bin/stop b/extras/pbbundler/smrtlink_services_ui/bin/stop
--- a/extras/pbbundler/smrtlink_services_ui/bin/stop
+++ b/extras/pbbundler/smrtlink_services_ui/bin/stop
@@ -18,7 +18,7 @@ SL_ANALYSIS_PID=$__root/sl-analysis.pid
 
 if [ -f ${SL_ANALYSIS_PID} ]; then
    PID=`cat ${SL_ANALYSIS_PID}`
-   echo Killing Java PID: ${SL_ANALYSIS_PID}
+   echo Killing Java PID: ${PID}
    kill $PID || true
    rm ${SL_ANALYSIS_PID}
 elif [ ! -f ${SL_ANALYSIS_PID} ]; then
@@ -26,11 +26,39 @@ elif [ ! -f ${SL_ANALYSIS_PID} ]; then
 fi
 
 STATUS=0
-ws02_dir="$__dir/../wso2am-2.0.0"
-bash $ws02_dir/bin/wso2server.sh --stop
+wso2_dir="$__dir/../wso2am-2.0.0"
+wso2_pid="$wso2_dir/wso2carbon.pid"
+if [ -f ${wso2_pid} ]; then
+   PID=`cat ${wso2_pid}`
+   echo "WSO2 PID: ${PID}"
+elif [ ! -f ${wso2_pid} ]; then
+   PID=0
+   echo "Could not locate WSO2 PID"
+fi
+bash $wso2_dir/bin/wso2server.sh --stop
 if [ $? -ne 0 ]; then
   STATUS=$?
   echo "WSO2 shutdown failed"
+fi
+if [ $PID -ne 0 ]; then
+  echo "Checking for lingering WSO2 process"
+  r=3
+  while [ $r -gt 0 ] && [ kill -0 "$PID" > /dev/null 2>&1 ]; do
+    echo "WSO2 still running on PID ${PID} (${r} retries)"
+    sleep 10s
+    r=$[$r-1]
+  done
+  if [ kill -0 "$PID" > /dev/null 2>&1 ]; then
+    echo "WSO2 still running on PID ${PID}"
+    echo "Sending termination signal to PID ${PID}"
+    kill $PID || true
+  fi
+  if [ kill -0 "$PID" > /dev/null 2>&1 ]; then
+    echo "WSO2 still running on PID ${PID}"
+    STATUS=1
+  fi
+elif [ $PID -eq 0 ]; then
+  echo "WARNING: WSO2 may still be running on unknown PID"
 fi
 
 $__dir/../apache-tomcat-8.0.26/bin/shutdown.sh
